### ISSUE TITLE
Not working with Steam new update

### ISSUE THREAD

**Issue by GeorgeV5601** [VaanaCZ/LANVP#18]
9mb update or something released, now the patch doesn't work. [V-Patch] Error while initializing patch, "Your version (2675) is not currently supported. Please contact the author as soon as possible, so that we can implement support for it!"

**Comment by Ryusennin** [comment]
Same with Rockstar version.

**Comment by VaanaCZ** [comment]
I have already implemented a fix for the Steam version. Now I only need to test it before it can be released.

Regarding the Rockstar Launcher version, I do not have it. If you want me to fix it I will need to have the main executable.

**Comment by Ryusennin** [comment]
I just contacted you via email.

**Comment by VaanaCZ** [comment]
@GeorgeV5601 @Ryusennin I've published a new release which should fix the aformentioned issues. I already tested the Steam version myself, but I couldn't the Rockstar Launcher version. There should be no issues though, since it was a simple 1:1 change between the previous version. If there are no further issues found, I'll close this issue.
[I](https://github.com/VaanaCZ/LANVP/releases/tag/v1.1b)
