### ISSUE TITLE
Can't lock FPS to 60

### ISSUE THREAD

**Issue by EntropyWasTaken** [VaanaCZ/LANVP#3]
So in the .ini file if I change the resolution output to 60 FPS it still keeps it unlocked for me. And playing at 144 is pretty bad, as the frame rate changing gives me stutters. Is there a way to lock it to 60 using your fix?

**Comment by VaanaCZ** [comment]
The refresh rate specified in the resolution option is there only to comply with the resolution string format used by the game. The patch does not do anything with it. It will most likely be removed in the next version of V-Patch, so that it doesn't cause confusion.

I will look into adding an separate FPS Cap option, since this might be useful to other people as well.

**Comment by VaanaCZ** [comment]
An FPS Cap option has been added in the latest release (v1.1).

After updating (and running the game at least once), simply open the config file, find the option `fps_lock` and set its value to your preferred framerate. 

In your case it should be `fps_lock=60`
