### ISSUE TITLE
Additional options

### ISSUE THREAD

**Issue by Patrxgt** [VaanaCZ/LANVP#5]
In "Planned features" you've wrote, that you want to add cut content and extra graphical options. Is there any possibility, that you could also implement options for:
- Skipping intro videos
- Unlocking exclusive for RGL version outfit
- Add early access to detective outfits

I know that **L.A. Noire Unlocker** adds options for that, but this mod colidates with mentioned before unlocker, so those can't be used at the same time.

**Comment by VaanaCZ** [comment]
> Skipping intro videos
This has already been implemented in the following version and will be available soon. 👍

> Unlocking exclusive for RGL version outfit
> Add early access to detective outfits
V-Patch is mainly intended to fix bugs and introduce quality of life features. I would consider adding such options if the outfits in question were unobtainable due to external factors (like an online service being shutdown). Otherwise, I do not wish to turn it into a cheat or trainer. Maybe in a new plugin that is separate from the main patch.

> I know that L.A. Noire Unlocker adds options for that, but this mod colidates with mentioned before unlocker, so those can't be used at the same time.
To my knowledge, L.A. Noire Unlocker is stuck on version 2617 and therefore, is incompatible with the latest Steam and R* Launcher builds. I am not aware of any potential conflict, other than the loading mechanism, between it and V-Patch, however, I have not checked myself.

**Comment by VaanaCZ** [comment]
The option to skip intro videos has been added in the latest release (v1.1)

To use it, update the patch and launch the game at least once. Then, open the config file (lanvp.ini), find the option `skip_logos` and simply set its value to 1. It should look like this: `skip_logos=1`

**Comment by Patrxgt** [comment]
> V-Patch is mainly intended to fix bugs and introduce quality of life features. I would consider adding such options if the outfits in question were unobtainable due to external factors (like an online service being shutdown). Otherwise, I do not wish to turn it into a cheat or trainer. Maybe in a new plugin that is separate from the main patch.
> 
Well, then at least add option to obtain R* Launcher exclusive outfit in Steam release.
